"""Central list of supported interface and generation languages."""

SUPPORTED_LANGUAGES = [
    "English",
    "Deutsch (German)",
    "Français (French)",
    "Italiano (Italian)",
    "Español (Spanish)",
    "Português (Portuguese)",
    "Svizzeru / Schweizerdeutsch (Swiss German)",
    "Rumantsch (Romansh)",
    "Albanian",
    "Bosnian",
    "Bulgarian",
    "Croatian",
    "Serbian",
    "Slovenian",
    "Romanian",
    "Russian",
    "Ukrainian",
    "Polish",
    "Czech",
    "Slovak",
    "Hungarian",
    "Turkish",
    "Arabic",
    "Hebrew",
    "Persian (Farsi)",
    "Kurdish",
    "Greek",
    "Filipino (Tagalog)",
    "Thai",
    "Vietnamese",
    "Malay / Indonesian",
    "Chinese (Simplified)",
    "Chinese (Traditional)",
    "Japanese",
    "Korean",
    "Hindi",
    "Urdu",
    "Bengali",
    "Punjabi",
    "Tamil",
    "Telugu",
    "Kannada",
    "Malayalam",
    "Sinhala",
    "Nepali",
    "Amharic",
    "Tigrinya",
    "Somali",
    "Swahili",
    "Yoruba",
    "Igbo",
    "Hausa",
    "Wolof",
    "Bambara",
    "Kinyarwanda",
    "Kirundi",
    "Lingala",
    "Zulu",
    "Xhosa",
    "Shona",
]
